/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesNewRouteImport } from './routes/properties_.new'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties_.$propertyId'
import { Route as OwnersNewRouteImport } from './routes/owners_.new'
import { Route as OwnersOwnerIdRouteImport } from './routes/owners_.$ownerId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings_.$bookingId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties_/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties_/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersNewRoute = OwnersNewRouteImport.update({
  id: '/owners_/new',
  path: '/owners/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersOwnerIdRoute = OwnersOwnerIdRouteImport.update({
  id: '/owners_/$ownerId',
  path: '/owners/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings_/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/owners': typeof OwnersRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/sign-in': typeof SignInRoute
  '/users': typeof UsersRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/new': typeof PropertiesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/owners': typeof OwnersRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/sign-in': typeof SignInRoute
  '/users': typeof UsersRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/new': typeof PropertiesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/owners': typeof OwnersRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/sign-in': typeof SignInRoute
  '/users': typeof UsersRoute
  '/bookings_/$bookingId': typeof BookingsBookingIdRoute
  '/owners_/$ownerId': typeof OwnersOwnerIdRoute
  '/owners_/new': typeof OwnersNewRoute
  '/properties_/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties_/new': typeof PropertiesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/forgot-password'
    | '/notifications'
    | '/owners'
    | '/profile'
    | '/properties'
    | '/sign-in'
    | '/users'
    | '/bookings/$bookingId'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/properties/$propertyId'
    | '/properties/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/forgot-password'
    | '/notifications'
    | '/owners'
    | '/profile'
    | '/properties'
    | '/sign-in'
    | '/users'
    | '/bookings/$bookingId'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/properties/$propertyId'
    | '/properties/new'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/forgot-password'
    | '/notifications'
    | '/owners'
    | '/profile'
    | '/properties'
    | '/sign-in'
    | '/users'
    | '/bookings_/$bookingId'
    | '/owners_/$ownerId'
    | '/owners_/new'
    | '/properties_/$propertyId'
    | '/properties_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  NotificationsRoute: typeof NotificationsRoute
  OwnersRoute: typeof OwnersRoute
  ProfileRoute: typeof ProfileRoute
  PropertiesRoute: typeof PropertiesRoute
  SignInRoute: typeof SignInRoute
  UsersRoute: typeof UsersRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  OwnersOwnerIdRoute: typeof OwnersOwnerIdRoute
  OwnersNewRoute: typeof OwnersNewRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesNewRoute: typeof PropertiesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties_/new': {
      id: '/properties_/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties_/$propertyId': {
      id: '/properties_/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners_/new': {
      id: '/owners_/new'
      path: '/owners/new'
      fullPath: '/owners/new'
      preLoaderRoute: typeof OwnersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners_/$ownerId': {
      id: '/owners_/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/owners/$ownerId'
      preLoaderRoute: typeof OwnersOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings_/$bookingId': {
      id: '/bookings_/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NotificationsRoute: NotificationsRoute,
  OwnersRoute: OwnersRoute,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRoute,
  SignInRoute: SignInRoute,
  UsersRoute: UsersRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  OwnersOwnerIdRoute: OwnersOwnerIdRoute,
  OwnersNewRoute: OwnersNewRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesNewRoute: PropertiesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
